INSERT INTO CUSTOMER(ADDRESS, NAME, PHONE_NUMBER, USER_NAME, PASSWORD) VALUES ('Test Address', 'Test customer name', '+84000000000', 'test', 'testpass');

INSERT INTO USER_OPERATOR(USER_NAME, PASSWORD) VALUES ('useroperator', 'useroperatorpass');

INSERT INTO SHOP(LONGITUDE, LATITUDE, CONTACT_DETAIL, MAXIMUM_SIZE_OF_QUEUE, CURRENT_NUMBER_OF_QUEUE, OPEN_TIME, CLOSE_TIME, USER_OPERATOR_ID) VALUES (10.00, 10.00, 'Shop Contact Details', 10, 0, '08:00:00', '22:30:00', 1);

INSERT INTO MENU_ITEM(ITEM_NAME, PRICE, SHOP_ID) VALUES ('Cool Coffee', 15000, 1);
INSERT INTO MENU_ITEM(ITEM_NAME, PRICE, SHOP_ID) VALUES ('Warn Coffee', 16000, 1);
