package com.interview.project.security;

public enum SystemRole {
    ADMIN,
    CORNERSTONE_ADMIN,

    INDIVIDUAL_POLICY_SELF,
    INDIVIDUAL_POLICY_MASTER,
    INDIVIDUAL_POLICY_UPLOAD,
    INDIVIDUAL_POLICY_READONLY,

    CORPORATE_POLICY_SELF,
    CORPORATE_POLICY_MASTER,
    CORPORATE_POLICY_UPLOAD,
    CORPORATE_POLICY_READONLY,

    CORPORATE_MASTER,
    CORPORATE_SELF,
    CORPORATE_READONLY,

    CORPORATE_MEMBER_MASTER,
    CORPORATE_MEMBER_SELF,
    CORPORATE_MEMBER_READONLY,

    KYC_MASTER,
    KYC_SELF,
    KYC_APPROVAL,
    KYC_READONLY,

    QUOTATION_MASTER,
    QUOTATION_SELF,
    QUOTATION_READONLY,

    PRODUCTION_MASTER,
    PRODUCTION_SELF,
    PRODUCTION_UPLOAD,
    PRODUCTION_READONLY
}
